menu_options = ds_list_create()
upgrades = ds_list_create()
shop_characters = ds_list_create()
shop_stages = ds_list_create()
menu = 0
selected = 0
ds_list_add(menu_options, ["UPGRADES", "get upgrades for more points per run!"])
ds_list_add(menu_options, ["CHARACTERS", "get characters to become your victims or the killer!"])
ds_list_add(menu_options, ["STAGES", "get stages to kill people in!"])
ds_list_add(upgrades, ["MORE POWER", (10 + (5 * global.powerlevel)), ("launch the noise farther. current power: " + string(global.power))])
ds_list_add(upgrades, ["MORE BOUNCE", (10 + (5 * global.bouncelevel)), ("makes the noise bounce more. current bounce: " + string(global.bounce))])
ds_list_add(shop_characters, ["GUSTAVO AND BRICK", 25, "it's their hour now!", "G", sfx_gustavosuper, sfx_gustavoscream, make_color_rgb(125, 81, 30)])
ds_list_add(shop_characters, ["PEPPERMAN", 75, "truly the perfect pepper", "M", sfx_peppermansuper, sfx_peppermanscream, 255])
ds_list_add(shop_characters, ["THE VIGILANTE", 150, "make the noise eat lead", "V", sfx_vigilantesuper, sfx_vigilantescream, 4235519])
ds_list_add(shop_characters, ["FAKE PEPPINO", 220, "nothing compares!", "F", sfx_fakepepsuper, sfx_fakepepscream, 8421504])
ds_list_add(shop_characters, ["PIZZAFACE", 350, "it's showtime", "Z", sfx_pizzafacesuper, sfx_pizzafacescream, make_color_rgb(224, 136, 88)])
ds_list_add(shop_characters, ["PIZZAHEAD", 500, "silly goober 2", "H", sfx_pizzaheadsuper, sfx_pizzaheadscream, make_color_rgb(48, 168, 248)])
ds_list_add(shop_characters, ["SNICK", 750, "it's him", "S", sfx_none, sfx_none, 8388736])
ds_list_add(shop_stages, ["JOHN GUTTER", 50, "favourable p rank location", rm_john])
ds_list_add(shop_stages, ["PIZZASCAPE", 50, "i actually don't know what to put here", rm_pizzascape])
ds_list_add(shop_stages, ["ANCIENT CHEESE", 50, "it smells... cheesy", rm_ancientcheese])
ds_list_add(shop_stages, ["BLOODSAUCE DUNGEON", 50, "has a roof and looks cool", rm_dungeon])
ds_list_add(shop_stages, ["OREGANO DESERT", 100, "why are there a thousand pizzamarts ahead", rm_desert])
ds_list_add(shop_stages, ["WASTEYARD", 100, "ooo spooky", rm_graveyard])
ds_list_add(shop_stages, ["FUN FARM", 100, "no mort to be found sadly", rm_farm])
ds_list_add(shop_stages, ["FAST FOOD SALOON", 100, "the walls in the back might look a bit trippy", rm_saloon])
ds_list_add(shop_stages, ["CRUST COVE", 150, "come in mr dj!", rm_beach])
ds_list_add(shop_stages, ["GNOME FOREST", 150, "lario", rm_forest])
ds_list_add(shop_stages, ["DEEP DISH 9", 150, "kill the olives for extra pizza points!", rm_space])
ds_list_add(shop_stages, ["GOLF", 150, "go through the golf hoops for pizza points!", rm_golf])
ds_list_add(shop_stages, ["PIG CITY", 200, "oink", rm_city])
ds_list_add(shop_stages, ["PEPPIBOT FACTORY", 200, "i am robot", rm_factory])
ds_list_add(shop_stages, ["OH SHIT", 200, "haha funni poop joke", rm_sewer])
ds_list_add(shop_stages, ["R-R-FREEZERATOR", 200, "there are ice chunks scattered in it that the noise can bounce in!", rm_freezer])
ds_list_add(shop_stages, ["PIZZASCARE", 250, "ooo spooky but again", rm_chateau])
ds_list_add(shop_stages, ["DON'T MAKE A SOUND", 250, "shhhhhh", rm_kidsparty])
ds_list_add(shop_stages, ["WAR", 250, "the war", rm_war])
menu_count = ds_list_size(menu_options)
upgrade_count = ds_list_size(upgrades)
character_count = ds_list_size(shop_characters)
stage_count = ds_list_size(shop_stages)
image_speed = 0.4
