draw_set_color(c_black)
draw_set_alpha(0.8)
draw_rectangle(0, 0, display_get_gui_width(), display_get_gui_height(), false)
draw_set_alpha(1)
draw_set_color(c_white)
draw_set_font(fnt_gamefont40)
draw_set_halign(fa_center)
draw_set_valign(fa_middle)
draw_text((display_get_gui_width() / 2), ((display_get_gui_height() / 2) - 100), (("YOU UNLOCKED A NEW " + unlock_type) + ":"))
draw_set_font(fnt_gamefont60)
draw_text((display_get_gui_width() / 2), (display_get_gui_height() / 2), unlock_name)
draw_set_valign(fa_top)
draw_text((display_get_gui_width() / 2), (display_get_gui_height() - 100), "PRESS 'Z' TO CLOSE")
